:pencil: update install doc + troubleshooting
CAMAP-APP/camap-ts pull request #15
Opened 2024-05-14 11:43 UTC by Johbrun

2024-05-14 12:08 UTC, Lythom requested changes
Aussi: supprimer le fichier my.cnf puisque cette config est déplacée vers le projet camap-docker (en même temps que de rajouter le fichier dans l'autre projet)

2024-05-14 12:08 UTC, Lythom commented on docs/install.md
>  ### camap-ts
Proposition: Ajouter un lien vers troubleshooting depuis install.md pour indiquer son existence.

2024-05-14 12:41 UTC, Mandrak-Kimigo commented
> Aussi: supprimer le fichier my.cnf puisque cette config est déplacée vers le projet camap-docker (en même temps que de rajouter le fichier dans l'autre projet)

Ne pas déplacer le fichier my.cnf vers Camap-docker: l'installation de prod/staging sur le serveur interamap44 n'utilise pas Camap-docker.

La vocation de Camap-docker est de permettre une installation stand-alone pour une AMAP ou pour le dev, mais sur un serveur de prod ce n'est pas vraiment adapté. Il faut donc que camap-ts et camap-hx restent "complet" à l'exception de la conf docker.

2024-05-14 13:00 UTC, Lythom commented
> Ne pas déplacer le fichier my.cnf vers Camap-docker: l'installation de prod/staging sur le serveur interamap44 n'utilise pas Camap-docker.
> 
> La vocation de Camap-docker est de permettre une installation stand-alone pour une AMAP ou pour le dev, mais sur un serveur de prod ce n'est pas vraiment adapté. Il faut donc que camap-ts et camap-hx restent "complet" à l'exception de la conf docker.

Concrètement ça ne changerait pas grand chose, Le fichier est une référence de config à utiliser lors de l'installation.
Interamap44 a déjà copié la config en question dans son image / répertoire MySQL.
Même si le fichier de config change de projet il sera toujours référencé par la doc (qui préconise camap-docker pour une nouvelle installation) et servira de référence même si les images dockers ne sont pas utilisées.

Le seul inconvénient de laisser le fichier dans camap-ts c'est qu'il est un peu caché et pas évident à trouver alors qu'avec le reste des configs de référence on le trouvera plus facilement.
Cela étant on peut tout à fait le laisser là pour les cas que tu décris où on veut retrouver cette config sans avoir à lire ou cloner camap-docker.

2024-05-21 15:42 UTC, Lythom approved these changes

2024-05-21 15:42 UTC, merged